export const UserInforConstance = {
  vi: {
    title: "Thông tin cá nhân",
    formLabel: {
      EmployeeCode: "Mã nhân viên",
      FullName: "Họ và tên",
      Mobile: "Số điện thoại",
      Department: "Đơn vị",
      Position: "Chức danh",
      Gender: "Giới tính",
      DateOfBirth: "Ngày sinh",
      Address: "Địa chỉ",
      PersonalIdentification: "Số CCCD",
      PersonalIdentificationTooltip: "Số căn cước công dân",
      PICreatedDate: "Ngày cấp",
      PICreatedPlace: "Nơi cấp",
      BankAccount: "Số tài khoản ngân hàng",
      BankName: "Tên ngân hàng",
      BankBranch: "Chi nhánh ngân hàng",
      chooseImage: "Chọn hình ảnh",
      ChooseDepartmentBefore: "Vui lòng chọn đơn vị trước",
      Vehicle: "Loại xe",
    },
    updateInforButton: "Cập nhật thông tin cá nhân",
    save: "Lưu",
    cancelUpdate: "Hủy thay đổi",
    toast: {
      UpdateUserInforSuccess: {
        summary: "Thành công",
        detail: "Cập nhật thông tin cá nhân thành công",
        severity: "success",
        life: 5000,
      },
    },
  },
  en: {
    title: "User information",
    formLabel: {
      EmployeeCode: "EmployeeCode",
      FullName: "Full name",
      Mobile: "Mobile",
      Department: "Department",
      Position: "Postion",
      Gender: "Gender",
      Address: "Address",
      DateOfBirth: "Date of birth",
      PersonalIdentification: "Citizen Identification Number",
      PersonalIdentificationTooltip: "Citizen Identification Number",
      PICreatedDate: "Date of Issue",
      PICreatedPlace: "Place of Issue",
      BankAccount: "Bank Account",
      BankName: "Bank Name",
      BankBranch: "Bank Branch",
      chooseImage: "Choose an image",
      ChooseDepartmentBefore: "Please select one department",
      Vehicle: "Vehicle",
    },
    updateInforButton: "Update personal information",
    save: "Save",
    cancelUpdate: "Cancel changes",
    toast: {
      UpdateUserInforSuccess: {
        summary: "Success",
        detail: "Personal information updated successfully",
        severity: "success",
        life: 5000,
      },
    },
  },
};
